version: "3"
services:
  ndn-node-1:
    build:
      context: .
    working_dir: /workspaces
    networks:
      ndn-network:
        # ipv4_address: 172.22.0.2
    volumes:
      - .:/workspaces
    tty: true
    stdin_open: true
    command: >
      bash -c "
      ./restart.sh && 
      ./auto_nlsr.sh 1 &&
      tail -f /dev/null
      "
    environment:
      - FUNCITON_FILE_PATH=/workspaces/config/function/function-a.py
      - NLSR_CONFIG_FILE_PATH=/workspaces/generated/nlsr/nlsr-1.conf
  ndn-node-2:
    build:
      context: .
    working_dir: /workspaces
    networks:
      ndn-network:
        # ipv4_address: 172.22.0.3
    volumes:
      - .:/workspaces
    tty: true
    stdin_open: true
    command: >
      bash -c "
      ./restart.sh && 
      ./auto_nlsr.sh 2 &&
      tail -f /dev/null
      "
    environment:
      - FUNCITON_FILE_PATH=/workspaces/config/function/function-a.py
      - NLSR_CONFIG_FILE_PATH=/workspaces/generated/nlsr/nlsr-2.conf
  ndn-node-3:
    build:
      context: .
    working_dir: /workspaces
    networks:
      ndn-network:
        # ipv4_address: 172.22.0.4
    volumes:
      - .:/workspaces
    tty: true
    stdin_open: true
    # command: |
    #   ./restart.sh && 
    #   ./auto_nlsr.sh 2 &&
    #   tail -f /dev/null
    environment:
      - FUNCITON_FILE_PATH=/workspaces/config/function/function-a.py

networks:
  ndn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
